version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./bakemate_dev.db:/app/bakemate_dev.db # Mount the SQLite DB
    environment:
      - DATABASE_URL=sqlite:///./bakemate_dev.db
      - SQLITE_DB_PATH=/app/bakemate_dev.db # Added for clarity within the app if needed
      - AIRTABLE_BASE_ID=${AIRTABLE_BASE_ID}
      - AIRTABLE_API_KEY=${AIRTABLE_API_KEY}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload # for development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Nginx in frontend Dockerfile serves on port 80
    volumes:
      - ./frontend/src:/app/src # Mount src for hot-reloading if dev server supports it
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/certs:/etc/nginx/certs:ro # For SSL certificates (Certbot)
    depends_on:
      - frontend
      - backend

volumes:
  # Define named volumes if needed for persistent data outside of bind mounts
  # e.g., postgres_data:
  bakemate_db_data: # For SQLite if not using a file in the repo for dev
