name: BakeMate CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  lint-and-test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest # Add any other linting/testing tools
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        # pytest # Add your test command here once tests are written
        echo "Pytest tests would run here"

  lint-and-test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: "20.x"
    - name: Install dependencies
      run: npm install
    - name: Lint with ESLint (Placeholder)
      run: echo "ESLint would run here. Configure package.json scripts."
      # Example: npm run lint
    - name: Test with Jest/Vitest (Placeholder)
      run: echo "Frontend tests would run here. Configure package.json scripts."
      # Example: npm test

  build-docker-images:
    runs-on: ubuntu-latest
    needs: [lint-and-test-backend, lint-and-test-frontend]
    steps:
    - uses: actions/checkout@v3
    - name: Build Backend Docker image
      run: docker build -t bakemate-backend:latest -f backend/Dockerfile .
    - name: Build Frontend Docker image
      run: docker build -t bakemate-frontend:latest -f frontend/Dockerfile .

