name: CI Test Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: pytest --cov=app --cov-report=xml
    - name: Enforce coverage
      run: |
        TOTAL=$(python - <<'PY'
import xml.etree.ElementTree as ET, sys
tree=ET.parse('coverage.xml'); rate=float(tree.getroot().attrib['line-rate'])
print(int(rate*100)); PY)
        if [ "$TOTAL" -lt 80 ]; then
          echo "Coverage $TOTAL% below target"; exit 1; fi
